language: php

sudo: false

php:
    - 7.3
    - 7.4

jobs:
    include:
        - php: nightly
          env: COMPOSER_FLAGS='--ignore-platform-reqs'
    allow_failures:
        - php: nightly


install: composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit --coverage-text
